don't use the database during download
allartk/leaflet.offline pull request #161
Opened 2022-03-18 20:10 UTC by harry-73

The use of the database during the download process means that the display of the map in real time may be altered. 
The goal in this case is to download the images.
At the end of the process, the database is used again

2022-03-25 10:19 UTC, harry-73 commented
Hi, did you have time to review it?

2022-03-25 13:13 UTC, allartk commented
No, sorry, not yet

2022-03-26 08:24 UTC, allartk commented
There are some linting errors, maybe you can add eslint to your editor, such as [vscode](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) please, or run manual `npm run lint` to check your syntax before commit? 
Besides, I have some doubts, why throw an exception, if you want to prevent the map view from being changed, I think you should do it at the map level, and we could document that?

2022-03-26 18:41 UTC, harry-73 commented
> There are some linting errors, maybe you can add eslint to your editor, such as [vscode](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) please, or run manual `npm run lint` to check your syntax before commit? 

I have installed it yesterday for my own development. Now, It should be OK. The last commit is OK. Sorry for that.

> Besides, I have some doubts, why throw an exception, if you want to prevent the map view from being changed, I think you should do it at the map level, and we could document that?

I am not sure to understand, I do want to prevent the map view from being changed but I want to be able, during the downloaded process, to have the tiles displayed when I move into it

2022-03-27 18:40 UTC, allartk commented
Let me ask it differently, you are trying to block the map from moving or zooming (and downloading new tiles) during download? If yes, I see it as a user interface thing (eg block map input with a html overlay)

2022-03-28 07:25 UTC, harry-73 commented
If that was my intention, I agree, it should be done at the Map level.
In fact, I noticed that during the tile download process, writing to the database was competing with reading from the tiles to display the map when moving it.
The purpose here is to avoid using the database while the download process is running. This allows to continue to have a smooth user experience.

2022-03-29 06:50 UTC, allartk commented
It's clear now, i forgot about the catch for this exception. I will leave some small comments and it can be merged.

2022-03-29 06:51 UTC, allartk commented on src/TileLayerOffline.js
> +          throw new Error('On download state');
Without testing, I excpect this can be replaced with
```
return Promise.reject('On download state');
```

2022-03-29 06:55 UTC, allartk requested changes
Sorry for being so slow and misunderstanding :) Just a small change and after it I'll merge (and make a 2.x release when I've got some time).

Are you willing to do some merging (in a separate branch) with the typescripted dev branch?

2022-03-29 17:47 UTC, allartk approved these changes

2022-03-29 17:47 UTC, merged

2022-03-29 19:05 UTC, harry-73 commented
> Are you willing to do some merging (in a separate branch) with the typescripted dev branch?

I know nothing about typescript  or very few...